### ISSUE TITLE
Static Commands

### ISSUE THREAD

**Issue by briamkin** [levibostian/betterBuster#5]
Hey Levi!
I'm attempting to use static but after cloning it and running the installs, bash still says that the static command doesn't exist... ruby lib/main.rb -h gives me the commands but none of them work. Am I missing a step here? What do you mean by run the program in the installation instructions?

**Comment by levibostian** [comment]
I am so so so sorry for just getting to this @Jakehp. I thought that because I created this repo I would automatically "watch" it to get email notifications on pull requests but I guess not so I just now found this. I am watching it now so it wont happen again....

Anyway, you are correct. That "static" command does not exist in bash. That is because when you install static, it is just simply a ruby script. It does not add the program "static" to your $PATH variable which bash would then pick up. So instead of running the program "static" from your bash command line, you must be in the directory of the cloned source code and then run `ruby lib/main.rb` like you mentioned. That is the only way to use the program right now. 

So if you wanted to run the generate command for example, you would do: `ruby lib/main.rb generate --site=levibostian.com` to generate a static version of the site "levibostian.com" (make sure to run the `add` or `setup` commands for your site before running generate or else it will error). 

I am wanting to get the program to install correctly so instead of `ruby lib/main.rb` you can just use `static` but not sure exactly how to do that yet. My guess is to create a ruby gem for the program? If anyone wants to take a stab at this I am certainly up for it. But until then, do `ruby lib/main.rb` for all commands.

**Comment by levibostian** [comment]
Created an issue for this https://github.com/levibostian/static/issues/5. Thanks! Any questions, please ask and I can help out.
